version: '2'
services:

  # MySQL setup
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./vaccinations.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --innodb-buffer-pool-size=25M

  # Grafana setup
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '80:3000'
    environment:
      GF_INSTALL_PLUGINS: percona-percona-app
      GRAFANA_ADMIN_USER: admin
      GRAFANA_ADMIN_PASSWORD: admin
      GF_AUTH_ORG_ROLE: viewer
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    volumes:
      - ./dashboards/:/etc/grafana/provisioning/dashboards/
      - ./datasources/:/etc/grafana/provisioning/datasources/
